### PR TITLE
Enriching orders with customerRemoteID for arrays

### PR DESCRIPTION
**Pull request by jdunn89**

### CODE REVIEW

**Comment by ekersey** [comment]
Is there a reason that "Header_BillToCustNo" is set on arrays but not on single objects?

**Comment by jdunn89** [comment]
"Header_BillToCustNo" is a field that Dan needs for Craft. The endpoint they're using is custom and the stub function wasn't designed around arrays originally.

**Comment by ekersey** [comment]
So, "payload.doc[orderServiceName]" being an array of objects, and those objects having a "Header_BillToCustNo" property on them are both things that are custom to Craft?

**Comment by jdunn89** [comment]
Right.

**Pull request merged**
